version: '3'
services:
  web:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/html/
  depends_on:
    - db
  command: sh -c "sleep 10 && apache2-foreground"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Dresser
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
