version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./mysql/dockerfile.yaml
    image: tutorial-db
    restart: always
    ports:
      - 3307:3307
  app:
    build:
      context: .
      dockerfile: ./php/dockerfile.yaml
    image: tutorial-php
    restart: always
    ports:
      - 8000:8000
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/usr/src/app/php
    command: composer install --ignore-platform-reqs
